<?php

/**
 * 菜单规则配置
 * 从 condoradmin.sql 的 con_system_menu_rule 表导入
 */

return [
    [
        'id' => 1,
        'is_keep' => 1,
        'pid' => 0,
        'name' => 'home',
        'title' => '控制台',
        'icon' => 'mdi:monitor-dashboard',
        'path' => '/home',
        'component' => 'layout.base$view.home',
        'i18nkey' => 'route.home',
        'remark' => '',
        'hidden' => 0,
        'redirect' => null,
        'menu_type' => 1,
        'href' => '',
        'active_menu' => '',
        'multi_tab' => null,
        'fixed_tab_index' => null,
        'query' => null,
        'weigh' => 0,
        'status' => 1,
        'createtime' => 1762870065,
        'updatetime' => 1767949463,
        'deleted_at' => null,
    ],
    [
        'id' => 2,
        'is_keep' => 1,
        'pid' => 0,
        'name' => 'system',
        'title' => '系统管理',
        'icon' => 'carbon:cloud-service-management',
        'path' => '/system',
        'component' => 'layout.base',
        'i18nkey' => 'route.system',
        'remark' => '',
        'hidden' => 0,
        'redirect' => null,
        'menu_type' => 1,
        'href' => null,
        'active_menu' => null,
        'multi_tab' => null,
        'fixed_tab_index' => null,
        'query' => null,
        'weigh' => 1,
        'status' => 1,
        'createtime' => 1762870065,
        'updatetime' => 1769592992,
        'deleted_at' => null,
    ],
    [
        'id' => 3,
        'is_keep' => 1,
        'pid' => 9,
        'name' => 'system_menu',
        'title' => '菜单管理',
        'icon' => 'material-symbols:route',
        'path' => '/system/menu',
        'component' => 'view.system_menu',
        'i18nkey' => 'route.system_menu',
        'remark' => '',
        'hidden' => null,
        'redirect' => null,
        'menu_type' => 1,
        'href' => null,
        'active_menu' => null,
        'multi_tab' => null,
        'fixed_tab_index' => null,
        'query' => null,
        'weigh' => 0,
        'status' => 1,
        'createtime' => 1762870065,
        'updatetime' => 1769593759,
        'deleted_at' => null,
    ],
];
